config/urls.py
from django.contrib import admin
from django.urls import path, include
from students.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('', home, name='home'),
]

groups/urls.py
from django.urls import path
from . import views


app_name = 'groups'

urlpatterns = [
    path('', views.group_list, name='group_list'),
    path('group/create', views.group_form, name='group_form'),
    path('detail/<int:pk>/', views.group_detail, name='group_detail'),
    path('delete/<int:pk>/', views.group_delete, name='group_delete'),
]

students/urls.py
from django.urls import path
from . import views


app_name = 'students'

urlpatterns = [
    path('', views.student_list, name='student_list'),
    path('student/form', views.student_form, name='student_form'),
    path('detail/<int:pk>/', views.student_detail, name='student_detail'),
    path('delete/<int:pk>/', views.student_delete, name='student_delete'),
]

teachers/urls.py
from django.urls import path
from . import views


app_name = 'teachers'

urlpatterns = [
    path('', views.teacher_list, name='teacher_list'),
    path('create/', views.teacher_form, name='teacher_form'),
    path('detail/<int:pk>/', views.teacher_detail, name='teacher_detail'),
    path('delete/<int:pk>/', views.teacher_delete, name='teacher_delete'),
]

groups/models.py
from django.db import models


class Group(models.Model):
    group_name = models.CharField(max_length=50)
    group_type = models.CharField(max_length=20)

students/models.py
from django.db import models


class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    age = models.PositiveIntegerField()
    email = models.EmailField(unique=True)

teachers/models.py
from django.db import models


class Teacher(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)

groups/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Group


def group_list(request):
    groups = Group.objects.all()
    ctx = {'groups': groups}
    return render(request, 'groups/group-list.html', ctx)

def group_form(request):
    if request.method == 'POST':
        group_name = request.POST.get('group_name')
        group_type = request.POST.get('group_type')
        if group_name and group_type:
            Group.objects.create(
                group_name = group_name,
                group_type = group_type
            )
            return redirect('groups:group_list')
    return render(request, 'groups/group-form.html')

def group_detail(request, pk):
    groups = get_object_or_404(Group, pk=pk)
    ctx = {'groups': groups}
    return render(request, 'groups/group-detail.html', ctx)

def group_delete(request, pk):
    groups = get_object_or_404(Group, pk=pk)
    groups.delete()
    return redirect('groups:group_list')

students/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Student


def home(request):
    return render(request, 'index.html')

def student_list(request):
    students = Student.objects.all()
    ctx = {'students': students}
    return render(request, 'students/student-list.html', ctx)

def student_form(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        age = request.POST.get('age')
        email = request.POST.get('email')
        if first_name and last_name and age and email:
            Student.objects.create(
                first_name=first_name,
                last_name= last_name,
                age=age,
                email=email
            )
            return redirect('students:student_list')
    return render(request, 'students/student-form.html')

def student_detail(request, pk):
    students = get_object_or_404(Student, pk=pk)
    ctx = {'students': students}
    return render(request, 'students/student-detail.html', ctx)

def student_delete(request, pk):
    students = get_object_or_404(Student, pk=pk)
    students.delete()
    return redirect('students:student_list')

teachers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Teacher


def teacher_list(request):
    teachers = Teacher.objects.all()
    ctx = {'teachers': teachers}
    return render(request, 'teachers/teacher-list.html', ctx)

def teacher_form(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        subject = request.POST.get('subject')
        if first_name and last_name and subject:
            Teacher.objects.create(
                first_name=first_name,
                last_name=last_name,
                subject=subject
            )
            return redirect('teachers:teacher_list')
    return render(request, 'teachers/teacher-form.html')


def teacher_detail(request, pk):
    teachers = get_object_or_404(Teacher, pk=pk)
    ctx = {'teachers': teachers}
    return render(request, 'teachers/teacher-detail.html', ctx)

def teacher_delete(request, pk):
    teachers = get_object_or_404(Teacher, pk=pk)
    teachers.delete()
    return redirect('teachers:teacher_list')

templates/groups/group-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ groups.group_name }} {{ groups.group_type }}</title>
</head>
<body>
    <h1>{{ groups.group_name }} {{ groups.group_type }}</h1>

    <h3>{{ groups.group_name }}</h3>
    <h3>{{ groups.group_type }}</h3>
    <br>
    <button><a href="{% url 'groups:group_delete' pk=groups.pk %}">Delete</a></button>
    <br><br>
    <button><a href="{% url 'groups:group_list' %}">Back to list</a></button><br>
</body>
</html>

templates/groups/group-form.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Group</title>
</head>
<body>
  <h1>Add Group</h1>
  <form method="post">
    {% csrf_token %}
    <label for="group_name">Group Name</label><br>
    <input type="text" name="group_name" id="group_name"><br><br>

    <label for="group_type">Group Type</label><br>
    <input type="text" name="group_type" id="group_type"><br><br>


    <input type="submit" value="Create Group"><br><br>
  </form>
    <button><a href="{% url 'groups:group_list' %}">Back to List</a></button><br><br>
      <button><a href="{% url 'home' %}">HOME</a></button><br><br>

</body>
</html>

templates/groups/group-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Group List</title>
</head>
<body>
    <h1>Group List</h1>
    <br>
    {% for groups in groups %}
        <a href="{% url 'groups:group_detail' pk=groups.pk %}"><h3>{{ groups.group_name }} {{ groups.group_type }}</h3></a>
    {% empty %}
        <h3>Not found</h3>
    {% endfor %}
  <button><a href="{% url 'home' %}">HOME</a></button><br><br>

    <button><a href="{% url 'groups:group_form' %}">Create Group</a></button>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
  <h1>Home</h1>
    <ol>
        <li><a href="{% url 'students:student_list' %}"><h3>Student List</h3></a></li>
        <li><a href="{% url 'groups:group_list' %}"><h3>Group List</h3></a></li>
        <li><a href="{% url 'teachers:teacher_list' %}">Teacher List</a></li>
    </ol>
</body>
</html>

templates/students/student-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ students.first_name }} {{ students.last_name }}</title>
</head>
<body>
    <h1>{{ students.first_name }} {{ students.last_name }}</h1>
    <h3>Age: {{ students.age }}</h3>
    <h3>Email: {{ students.email }}</h3>
    <br>
    <button><a href="{% url 'students:student_delete' pk=students.pk %}">Delete</a></button><br><br>
    <button><a href="{% url 'students:student_list' %}">Back to list</a></button>
</body>
</html>

templates/students/student-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Student</title>
</head>
<body>
  <h1>Add Student</h1>
  <form method="post">
    {% csrf_token %}
    <label for="first_name">First Name</label><br>
    <input type="text" name="first_name" id="first_name"><br><br>

    <label for="last_name">Last Name</label><br>
    <input type="text" name="last_name" id="last_name"><br><br>

    <label for="age">Age</label><br>
    <input type="number" name="age" id="age"><br><br>

    <label for="email">Email</label><br>
    <input type="text" name="email" id="email"><br><br>


    <input type="submit" value="Create Student"><br><br>
  </form>
    <button><a href="{% url 'students:student_list' %}">Back to List</a></button><br><br>
      <button><a href="{% url 'home' %}">HOME</a></button><br><br>

</body>
</html>

templates/students/student-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student List</title>
</head>
<body>
    <h1>Student List</h1>
    <br>
    {% for students in students %}
        <a href="{% url 'students:student_detail' pk=students.pk %}"><h3>{{ students.first_name }} {{ students.last_name }}</h3></a>
    {% empty %}
        <h3>Not found</h3>
    {% endfor %}
  <button><a href="{% url 'home' %}">HOME</a></button><br><br>

    <button><a href="{% url 'students:student_form' %}">Create Student</a></button>

</body>
</html>

templates/teachers/teacher-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ teachers.first_name }} {{ teachers.last_name }}</title>
</head>
<body>
    <h1>{{ teachers.first_name }} {{ teachers.last_name }}</h1>
    <h3>Subjects: {{ teachers.subject }}</h3>

    <br>
    <button><a href="{% url 'teachers:teacher_delete' pk=teachers.pk %}">Delete</a></button><br><br>
    <button><a href="{% url 'teachers:teacher_list' %}">Back to list</a></button>
</body>
</html>

templates/teachers/teacher-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Student</title>
</head>
<body>
  <h1>Add Student</h1>
  <form method="post">
    {% csrf_token %}
    <label for="first_name">First Name</label><br>
    <input type="text" name="first_name" id="first_name"><br><br>

    <label for="last_name">Last Name</label><br>
    <input type="text" name="last_name" id="last_name"><br><br>

    <label for="subject">Subject</label><br>
    <input type="text" name="subject" id="subject"><br><br>

    <input type="submit" value="Create Teacher"><br><br>
  </form>
    <button><a href="{% url 'teachers:teacher_list' %}">Back to List</a></button><br><br>
      <button><a href="{% url 'home' %}">HOME</a></button><br><br>

</body>
</html>

templates/teachers/teacher-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher List</title>
</head>
<body>
    <h1>Teacher List</h1>
    <br>
    {% for teachers in teachers %}
        <a href="{% url 'teachers:teacher_detail' pk=teachers.pk %}"><h3>{{ teachers.first_name }} {{ teachers.last_name }}</h3></a>
    {% empty %}
        <h3>Not found</h3>
    {% endfor %}
  <button><a href="{% url 'home' %}">HOME</a></button><br><br>

    <button><a href="{% url 'teachers:teacher_form' %}">Create Teacher</a></button>

</body>
</html>